image: Visual Studio 2017
version: 1.0.0.{build}
build_script:
- ps: .\ci\build-solution.ps1
test_script:
- ps: .\ci\run-test.ps1
artifacts:
- path: SumoLogic.Logging.Nuget\**.nupkg
deploy:
- provider: NuGet
  api_key:
    secure: You need to replace this sentense with an encrypted nuget key
  on:
    appveyor_repo_tag: true